title: Essays by Ekagra Sinha
baseurl: "/essays"  
url: "https://ekagra.github.io"
author: Ekagra Sinha
  
# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  essays:
    output: true
    permalink: /:title/
    sort_by: date

# Defaults
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "essay"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-seo-tag
